<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$product = $block->getProduct();
$enable = $this->helper('Project3\StockStatus\Helper\Data')->getConfig('stockstore/statuspage/enabled_status');
$status = $product->getData('custom_stock_status');
if($enable==1){
    $status = $product->getData('custom_stock_status');
}
else
    $status = null;

?>
<span class='wow1 tada' style="font-weight: bolder; color: #7d2717; font-size: 120%; text-align: center;"><?php echo $status; ?></span>
