<?php $_product = $block->getProduct(); 
?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=<?php echo $block->getData('app_id');?>";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-comments" data-href="<?php echo $block->getProductUrl($_product); echo "<script>console.log( 'Debug Objects: " . $block->getProductUrl($_product) . "' );</script>"; ?>" data-width="100%" data-numposts="8" data-show-faces="true"></div>